
networks:
  mml:
    external: false

services:
  auth:
    build: ./auth
    container_name: mml-auth
    restart: always
    depends_on:
      - database
    environment:
      - PORT=${AUTH_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    networks:
      - mml
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"

  modpacks:
    build: ./modpacks
    container_name: mml-modpacks
    restart: always
    environment:
      - PORT=${MODPACKS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    depends_on:
      - auth
      - database
    networks:
      - mml
    ports:
      - "${MODPACKS_PORT}:${MODPACKS_PORT}"

  database:
    image: postgres:16.8-alpine
    restart: always
    container_name: mml-database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - mml
